addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "1.0.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "5.0.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "1.1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"     % "1.0.8")
addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "2.2.1")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.5.1")